name: Build and Push to Docker

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  IMAGE_URI: alexswilliams/aws-tree

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build . --tag ${IMAGE_URI}:${GITHUB_SHA}

      - name: Log in to dockerhub
        run: docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push to dockerhub
        run: docker push ${IMAGE_URI}:${GITHUB_SHA}
