name: Release New Version

on:
  release:
    types:
      - created

env:
  IMAGE_URI: alexswilliams/aws-tree

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build . --tag ${IMAGE_URI}:${GITHUB_SHA}

      - name: Log in to dockerhub
        run: docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push to dockerhub
        run: docker push ${IMAGE_URI}:${GITHUB_SHA}

      - name: Tag as latest
        run: docker tag ${IMAGE_URI}:${GITHUB_SHA} ${IMAGE_URI}:latest

      - name: Update latest tag
        run: docker push ${IMAGE_URI}:latest
